In [69]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import warnings                                              
from sklearn.exceptions import DataConversionWarning          
warnings.filterwarnings(action='ignore', category=DataConversionWarning)

In [70]:
data= pd.read_csv('../training.csv')

In [71]:
data.head()

,Unnamed: 0,store_ID,day_of_week,date,nb_customers_on_day,open,promotion,state_holiday,school_holiday,sales
0,425390,366,4,2013-04-18,517,1,0,0,0,4422
1,291687,394,6,2015-04-11,694,1,0,0,0,8297
2,411278,807,4,2013-08-29,970,1,1,0,0,9729
3,664714,802,2,2013-05-28,473,1,1,0,0,6513
4,540835,726,4,2013-10-10,1068,1,1,0,0,10882

In [72]:
data.drop(columns=['Unnamed: 0', 'store_ID'], inplace=True)
data.head()

,day_of_week,date,nb_customers_on_day,open,promotion,state_holiday,school_holiday,sales
0,4,2013-04-18,517,1,0,0,0,4422
1,6,2015-04-11,694,1,0,0,0,8297
2,4,2013-08-29,970,1,1,0,0,9729
3,2,2013-05-28,473,1,1,0,0,6513
4,4,2013-10-10,1068,1,1,0,0,10882

In [73]:
print(data.isna().sum())
data.dtypes

day_of_week            0
date                   0
nb_customers_on_day    0
open                   0
promotion              0
state_holiday          0
school_holiday         0
sales                  0
dtype: int64

day_of_week             int64
date                   object
nb_customers_on_day     int64
open                    int64
promotion               int64
state_holiday          object
school_holiday          int64
sales                   int64
dtype: object

In [74]:
print(data)

        day_of_week        date  nb_customers_on_day  open  promotion  \
0                 4  2013-04-18                  517     1          0
1                 6  2015-04-11                  694     1          0
2                 4  2013-08-29                  970     1          1
3                 2  2013-05-28                  473     1          1
4                 4  2013-10-10                 1068     1          1
...             ...         ...                  ...   ...        ...
640835            6  2013-10-26                  483     1          0
640836            1  2014-04-14                  987     1          1
640837            1  2014-07-07                  925     1          0
640838            4  2014-06-12                  725     1          0
640839            7  2015-05-03                    0     0          0

       state_holiday  school_holiday  sales
0                  0               0   4422
1                  0               0   8297
2                  0               0   9729
3                  0               0   6513
4                  0               0  10882
...              ...             ...    ...
640835             0               0   4553
640836             0               0  12307
640837             0               0   6800
640838             0               0   5344
640839             0               0      0

[640840 rows x 8 columns]

In [75]:
import seaborn as sns
# sns.pairplot(data, diag_kind='kde')

In [ ]:
def one_hot_encode_state_holidays(df):
    return pd.get_dummies(df, columns=['state_holiday'], dtype=int)

df_1 = one_hot_encode_state_holidays(data)


def one_hot_encode_date(df):
    df['date'] = pd.to_datetime(df['date'])
    df['year'] = df['date'].dt.year
    df['month'] = df['date'].dt.month
    df['day'] = df['date'].dt.day
    df['day_of_week'] = df['date'].dt.dayofweek
    df['week_of_year'] = df['date'].dt.isocalendar().week.astype(int)
    df=df.drop(columns=['date'], axis=1)
    return df

df_2=one_hot_encode_date(df_1)

df_2.head()

cleaned_df=df_2

# df_2.dtypes

# df_2['week_of_year'].unique()

,day_of_week,nb_customers_on_day,open,promotion,school_holiday,sales,state_holiday_0,state_holiday_a,state_holiday_b,state_holiday_c,year,month,day,week_of_year
0,3,517,1,0,0,4422,1,0,0,0,2013,4,18,16
1,5,694,1,0,0,8297,1,0,0,0,2015,4,11,15
2,3,970,1,1,0,9729,1,0,0,0,2013,8,29,35
3,1,473,1,1,0,6513,1,0,0,0,2013,5,28,22
4,3,1068,1,1,0,10882,1,0,0,0,2013,10,10,41